In [38]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\onedrive\documents\data analytics\pydata\web scrapping\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\onedrive\documents\data analytics\pydata\web scrapping\venv\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\users\hp\onedrive\documents\data analytics\pydata\web scrapping\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp312-cp312-win_amd64.whl (9.7 MB)
Using cached numpy-2.5.3-cp312-cp312-win_amd64.whl (12.6 MB)
Installing collected packages: numpy, pandas
Successfully installed numpy-2.5.3 pandas-3.0.6
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd
import requests

In [10]:
response=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=4bc52c529a34c4c2126ce485dd1a6a06&language=en-US&page=1")

In [20]:
df=pd.DataFrame(response.json()["results"])[["id","title","overview","release_date","popularity","vote_average","vote_count"]]

In [23]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,70.3968,9.100,1273
1,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,44.3701,9.100,430
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,46.7178,8.900,2226
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,12.6550,8.832,393
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,55.4502,8.800,2248
5,1621552,Facing El Chapo,Two Mexican officers must survive the final ho...,2026-08-21,50.6797,8.783,884
6,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,58.3823,8.700,31511
7,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,58.3163,8.688,23698
8,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,91.1012,8.600,8161
9,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,53.5086,8.600,4492
10,1232449,Young Hearts,14-year-old Elias increasingly feels like an o...,2024-10-26,15.2985,8.599,323
11,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,36.5527,8.575,10440
12,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,38.9847,8.600,14420
13,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,33.3345,8.600,17997
14,1630423,My Dearest Assassin,"Hunted for her rare blood type, a caged woman ...",2026-05-06,16.9720,8.554,307
15,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,29.3178,8.500,1229
16,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,53.0858,8.537,36900
17,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,39.9545,8.500,19000
18,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,38.9441,8.500,19914
19,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,49.1518,8.500,27513

In [31]:
dfs=[]
for i in range(1,5):
    re=requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=4bc52c529a34c4c2126ce485dd1a6a06&language=en-US&page={}".format(i))
    tempdf=pd.DataFrame(re.json()["results"])[["id","title","overview","release_date","popularity","vote_average","vote_count"]]
    dfs.append(tempdf)
df = pd.concat(dfs, ignore_index=True)

In [32]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,70.3968,9.100,1273
1,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,44.3701,9.100,430
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,46.7178,8.900,2226
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,12.6550,8.832,393
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,55.4502,8.800,2248
...,...,...,...,...,...,...,...
75,533514,Violet Evergarden: The Movie,As the world moves on from the war and technol...,2020-09-18,8.1062,8.300,550
76,207,Dead Poets Society,"At an elite, old-fashioned boarding school in ...",1989-06-02,27.7965,8.300,13018
77,101,Léon: The Professional,"Léon, the top hit man in New York, has earned ...",1994-09-14,35.0279,8.300,16605
78,820067,The Quintessential Quintuplets Movie,When five lovely young girls who hate studying...,2022-05-20,7.1302,8.282,459
79,644479,Dedicated to my ex,"The film tells the story of Ariel, a 21-year-o...",2019-11-01,3.6342,8.300,514

In [39]:
df.to_excel("TMDB_TOP_MOVIE.xlsx", index=False)