In [2]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [20]:
url="https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1"
#befire header
# webpage=requests.get('url')
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
# after header
webpage=requests.get(url,headers=headers)

#### it's Showing error as we are not browser because robot.txt never allows bot to craul data before adding header

In [15]:
webpage

In [16]:
webpage.text

'<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;www&#46;ambitionbox&#46;com&#47;list&#45;of&#45;companies&#63;" on this server.<P>\nReference&#32;&#35;18&#46;d1cc517&#46;1791484269&#46;965052e\n<P>https&#58;&#47;&#47;errors&#46;edgesuite&#46;net&#47;18&#46;d1cc517&#46;1791484269&#46;965052e</P>\n</BODY>\n</HTML>\n'

#### After adding heder we can show we are browser

In [21]:
webpage

In [24]:
# webpage.text  this line will show comlete html code of our webpage

In [33]:
soup=BeautifulSoup(webpage.text,'html.parser')

In [38]:
#print(soup.prettify()) this line will write html code in proper hirarchy

In [65]:
soup.find_all("h2",class_="line-clamp-2")[0]

In [66]:
soup.find_all("h2",class_="line-clamp-2")[0].text

'TCS'

In [67]:
name=soup.find_all("h2",class_="line-clamp-2")

In [70]:
name[0]

In [71]:
len(name)

20

In [77]:
for i in name:
    print(i.text)

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Axis Bank
Jio
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTM Limited
HDB Financial Services

In [83]:
data=soup.find_all("div",class_="mb-5")

In [86]:
len(data)

21

In [114]:
company_name=[]
rating=[]
industry = []
location = []
for i in data:
    #headig
    head=i.find('h2')
    if head is None: #if h2 is not availabe i.e None it will rail error
        pass
    else:
        company_name.append(head.text)

    #rating
    ratng=i.find('div',class_="flex flex-row android:mb-[4px]")
    if ratng is None:
        pass
    else:
        rating.append(ratng.text)

    # Industry and Location
    span = i.find('span', class_="overflow-hidden text-left text-[14px] font-pn-400 leading-5 tracking-[0.25px] text-[#394468] max-md:text-[12px] max-md:leading-4")

    if span is None:
        pass
    else:
        text = span.get_text(strip=True)
        parts = text.split('|', 1)

        if len(parts) == 2:
            industry.append(parts[0].strip())
            location.append(parts[1].split('other locations')[0].strip())

In [118]:
df=pd.DataFrame({"name":company_name,
                "rating":rating,
                "industry":industry,
                "location":location})

In [119]:
df

                      name rating                  industry        location
0                      TCS    3.2  IT Services & Consulting  Bengaluru +491
1                Accenture    3.7  IT Services & Consulting  Bengaluru +288
2                    Wipro    3.6  IT Services & Consulting  Hyderabad +402
3                Cognizant    3.7  IT Services & Consulting  Hyderabad +259
4                Capgemini    3.6  IT Services & Consulting  Bengaluru +216
5                HDFC Bank    3.8                   Banking    Mumbai +1953
6                  Infosys    3.5  IT Services & Consulting  Bengaluru +266
7                  HCLTech    3.4  IT Services & Consulting  Bengaluru +260
8               ICICI Bank    3.9                   Banking    Mumbai +1498
9            Tech Mahindra    3.3  IT Services & Consulting  Hyderabad +342
10                 Genpact    3.6           Analytics & KPO  Hyderabad +196
11                     TP     3.8                       BPO     Mumbai +284
12               Axis Bank    3.6                   Banking    Mumbai +1594
13                     Jio    4.3                   Telecom    Mumbai +2008
14  Concentrix Corporation    3.5                       BPO  Bengaluru +209
15                  Amazon    3.9                  Internet  Bengaluru +558
16         Reliance Retail    3.9                    Retail    Mumbai +1219
17              iEnergizer    4.5                       BPO       Noida +58
18             LTM Limited    3.5  IT Services & Consulting  Bengaluru +160
19  HDB Financial Services    3.9                      NBFC    Mumbai +1150

In [72]:
dfs=[]
for j in range(1,10):
    url=f"https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={j}"
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
    webpage=requests.get(url,headers=headers)
    print("Page:", j, "Status:", webpage.status_code)
    soup=BeautifulSoup(webpage.text,"html.parser")
    dat = soup.find_all("div", class_="mb-5")
    
    company_name=[]
    rating=[]
    industry = []
    location = []
    for i in dat:
        #headig
        head=i.find('h2')
        if head is None: #if h2 is not availabe i.e None it will rail error
            pass
        else:
            company_name.append(head.text)
    
        #rating
        ratng=i.find('div',class_="flex flex-row android:mb-[4px]")
        if ratng is None:
            pass
        else:
            rating.append(ratng.text)
    
        # Industry and Location
        span = i.find('span', class_="overflow-hidden text-left text-[14px] font-pn-400 leading-5 tracking-[0.25px] text-[#394468] max-md:text-[12px] max-md:leading-4")
    
        if span is None:
            pass
        else:
            text = span.get_text(strip=True)
            parts = text.split('|', 1)
    
            if len(parts) == 2:
                industry.append(parts[0].strip())
                location.append(parts[1].split('other locations')[0].strip())
    df=pd.DataFrame({"name":company_name,
                "rating":rating,
                "industry":industry,
                "location":location})
    dfs.append(df)
if dfs:
    final = pd.concat(dfs, ignore_index=True)
else:
    final = pd.DataFrame()

Page: 1 Status: 200
Page: 2 Status: 200
Page: 3 Status: 200
Page: 4 Status: 200
Page: 5 Status: 200
Page: 6 Status: 200
Page: 7 Status: 200
Page: 8 Status: 200
Page: 9 Status: 200

In [73]:
final

                        name rating                  industry        location
0                        TCS    3.2  IT Services & Consulting  Bengaluru +491
1                  Accenture    3.7  IT Services & Consulting  Bengaluru +288
2                      Wipro    3.6  IT Services & Consulting  Hyderabad +402
3                  Cognizant    3.7  IT Services & Consulting  Hyderabad +259
4                  Capgemini    3.6  IT Services & Consulting  Bengaluru +216
..                       ...    ...                       ...             ...
95                   Blinkit    3.8                  Internet   Gurugram +215
96       Hindalco Industries    4.2           Metals & Mining  Sambalpur +137
97      Jindal Steel Limited    4.0              Iron & Steel      Angul +181
98  Macleods Pharmaceuticals    3.8                    Pharma     Mumbai +146
99  Carelon Global Solutions    3.9  IT Services & Consulting   Bengaluru +24

[100 rows x 4 columns]

In [74]:
final.to_excel("Companys.xlsx", index=False)